#!/usr/bin/env python3
"""Generate the desktop installer icons from the launcher icons already in the repository.

    python tools/make_desktop_icons.py

Writes `desktopApp/icons/`: `tto.icns` for the `.dmg`, `tto.ico` for the `.msi`, and
`tto.png` for the `.deb`. `desktopApp/build.gradle.kts` points `nativeDistributions` at
the three, and nothing else in the build reads them.


Why this does not read the AS3 source
-------------------------------------

`make_launcher_icons.py` reads `sources/assets/appIcons/icon_128.png` and needs the AS3 tree
checked out beside this one.  This script reads two files that are **committed here** instead:

* `mipmap-xxxhdpi/ic_launcher.png` -- the legacy launcher icon: the plate, shaped, with the
  wing on it, at 192 px.  The plate's gradient is recovered from it by measurement.
* `mipmap-xxxhdpi/ic_launcher_foreground.png` -- the wing on the 108 dp adaptive canvas, at
  432 px.  Its central 253 px square is the wing at plate scale, which is the same thing
  `legacy_icon` pastes.

So the desktop icons can be regenerated by anyone who has this repository, which is the
point: an artifact needed by a release job must not depend on a directory that only exists
on one machine.

`verify()` is what makes that safe.  It re-renders at 192 px and compares against the
committed legacy icon pixel by pixel; if the reconstruction below ever stops agreeing with
the one `make_launcher_icons.py` produced, this script fails instead of quietly shipping a
different icon on the desktop than on the phone.


The resolution ceiling is the art, not this script
--------------------------------------------------

The original is **128 px**.  Every launcher icon in the repository was derived from it, and so
is everything here.  macOS asks for 1024 px, so the largest `.icns` entry is an eight-fold
upscale of a smooth silhouette -- soft, and unavoidably so: regenerating from the AS3 source
would upscale the same 128 px by the same factor.

What that costs, in the sizes that are actually looked at:

| where | px | scale from source |
|---|---|---|
| Windows taskbar, Linux panel | 32-64 | a downscale |
| `.ico` largest, macOS Finder list | 256 | 2x |
| macOS Dock at 2x, Launchpad | 512 | 4x |
| `.icns` largest, Finder "Get Info" | 1024 | 8x |

The everyday sizes are fine.  Fixing the top two means new artwork, which is a drawing job and
not a build one.
"""

import pathlib
import struct
import sys

try:
    from PIL import Image, ImageDraw
except ImportError:  # pragma: no cover - a developer tool, not part of the build
    sys.exit("Pillow is required: python -m pip install pillow")

ROOT = pathlib.Path(__file__).resolve().parent.parent
RES = ROOT / "androidApp/src/main/res/mipmap-xxxhdpi"
LEGACY = RES / "ic_launcher.png"
FOREGROUND = RES / "ic_launcher_foreground.png"
OUT = ROOT / "desktopApp/icons"

#: Corner radius of the plate, as a fraction of its side. `make_launcher_icons.PLATE_CORNER`.
PLATE_CORNER = 59 / 128
#: Anti-aliasing factor for the synthesised plate. `make_launcher_icons.SUPERSAMPLE`.
SUPERSAMPLE = 4

#: `.ico` holds every size Windows asks for; 256 is the largest the format defines.
ICO_SIZES = (16, 24, 32, 48, 64, 128, 256)
#: The Linux `.deb` takes one PNG. 512 covers a HiDPI panel and every launcher menu.
PNG_SIZE = 512

#: `.icns` chunk types, as (OSType, pixel size). Everything from `ic07` up holds a PNG.
#: The `@2x` types carry the same pixels as their 1x twin at twice the size, which is why
#: 32/64/256/512 each appear once and serve both roles.
ICNS_TYPES = (
    (b"ic07", 128),
    (b"ic08", 256),
    (b"ic09", 512),
    (b"ic10", 1024),
    (b"ic11", 32),
    (b"ic12", 64),
    (b"ic13", 256),
    (b"ic14", 512),
)

#: How closely a re-render must match the committed launcher icon. See `verify`.
MAX_CHANNEL_DRIFT = 6
#: Of the pixels that are wholly plate or wholly wing, how many may miss that bar.
MAX_DRIFTING_PIXELS = 0.005
#: How much of the icon the wing's anti-aliased edge may occupy. A silhouette drawn at the
#: wrong size or in the wrong place inflates this before it inflates anything else.
MAX_EDGE_SHARE = 0.06


def wing_mask():
    """The wing at plate scale, cropped exactly as the legacy icon crops it.

    `adaptive_foreground` pastes `_wing(mask, plate)` centred on the 108 dp canvas, so the
    central square of that canvas is the wing the legacy icon uses. The plate side is derived
    from the two radii rather than written down, so this stays correct if either moves.
    """
    foreground = Image.open(FOREGROUND)
    canvas = foreground.size[0]
    # `make_launcher_icons.adaptive_foreground`, with SAFE_RADIUS / WING_RADIUS / ADAPTIVE_DP.
    plate = round(canvas * (33.0 / 66.7) * 128 / 108)
    offset = (canvas - plate) // 2
    return foreground.getchannel("A").crop(
        (offset, offset, offset + plate, offset + plate)
    )


def gradient_ends():
    """The plate's two corner colours, measured off the committed legacy icon.

    The plate is a linear gradient at 45 degrees, so its colour depends on `x + y` alone.
    That is what makes this a measurement and not a guess: every plate pixel on one
    anti-diagonal is one sample of the same value, and a straight line through the
    per-diagonal means recovers both ends.

    Read from the PNG rather than from `ic_launcher_background.xml`, whose endpoints are
    extrapolated **past** the plate and whose start channel is clipped at 255 — inverting that
    recovers red and green and silently loses blue by thirty levels.

    Wing pixels are excluded via the mask, and so are the rounded corners, where the PNG
    stores junk under a zero alpha.
    """
    icon = Image.open(LEGACY).convert("RGBA")
    side = icon.size[0]
    mask = wing_mask().resize((side, side), Image.LANCZOS)
    pixels, covered = icon.load(), mask.load()

    # sum and count per anti-diagonal, then a least-squares line through the means.
    totals = {}
    for y in range(side):
        for x in range(side):
            red, green, blue, alpha = pixels[x, y]
            if alpha < 250 or covered[x, y] > 5:
                continue
            entry = totals.setdefault(x + y, [0, 0, 0, 0])
            entry[0] += red
            entry[1] += green
            entry[2] += blue
            entry[3] += 1

    span = 2 * (side - 1)
    points = [(d / span, [entry[c] / entry[3] for c in range(3)]) for d, entry in totals.items()]
    return tuple(_line(points, channel) for channel in range(2))


def _line(points, end):
    """Least-squares `c = a + b*t` per channel, evaluated at t = 0 (end 0) or t = 1 (end 1)."""
    out = []
    for channel in range(3):
        n = len(points)
        st = sum(t for t, _ in points)
        stt = sum(t * t for t, _ in points)
        sc = sum(c[channel] for _, c in points)
        stc = sum(t * c[channel] for t, c in points)
        denominator = n * stt - st * st
        slope = (n * stc - st * sc) / denominator
        intercept = (sc - slope * st) / n
        out.append(_byte(intercept + slope * end))
    return tuple(out)


def _byte(value):
    return max(0, min(255, round(value)))


def _wing(mask, size):
    """`make_launcher_icons._wing`: resample, then put the edge back where it was."""
    scaled = mask.resize((size, size), Image.LANCZOS)
    factor = size / mask.size[0]
    if factor <= 1.0:
        return scaled
    lut = [_byte(128 + (value - 128) * factor) for value in range(256)]
    return scaled.point(lut)


def icon(ends, mask, size):
    """The plate at `size` px, shaped and with the wing on it — `legacy_icon`, standalone."""
    start, end = ends
    big = size * SUPERSAMPLE

    plate = Image.new("RGBA", (big, big))
    pixels = plate.load()
    for y in range(big):
        row = y / (2 * (big - 1))
        for x in range(big):
            t = row + x / (2 * (big - 1))
            pixels[x, y] = tuple(_byte(a + (b - a) * t) for a, b in zip(start, end)) + (255,)

    shape = Image.new("L", (big, big), 0)
    ImageDraw.Draw(shape).rounded_rectangle(
        (0, 0, big - 1, big - 1), radius=round(big * PLATE_CORNER), fill=255
    )
    plate.putalpha(shape)

    small = plate.resize((size, size), Image.LANCZOS)
    small.paste(Image.new("RGBA", (size, size), (255, 255, 255, 255)), (0, 0), _wing(mask, size))
    # The wing overhangs the plate's corners, so re-apply the silhouette.
    small.putalpha(
        Image.composite(
            small.getchannel("A"),
            Image.new("L", (size, size), 0),
            shape.resize((size, size), Image.LANCZOS),
        )
    )
    return small


def verify(ends, mask):
    """Re-render at the legacy icon's own size and insist the two agree.

    Not a formality. Everything above is a *reimplementation* of `make_launcher_icons`, from
    different inputs, and the failure it can have is silent: an icon that is recognisably the
    right thing and subtly not the shipped one, so the phone and the desktop disagree about
    what this application looks like.

    ### Why the wing's edge is exempt, and what replaces the exemption

    Pixel-for-pixel equality is not reachable and the reason is structural, not sloppy. The
    committed icon holds `_wing(mask@128, 192)` — one upscale from the original. This script
    only has the 253 px wing that upscale already produced, so it renders
    `_wing(mask@253, 192)`: the same silhouette through **two** resamplings instead of one.
    That moves the anti-aliased boundary by a fraction of a pixel, and on a boundary between
    white and a mid-blue plate a fraction of a pixel is a difference of 255.

    Exempting it would be an exemption for the only part that can be wrong, so it is replaced
    rather than granted:

    * every pixel that is **wholly plate** or **wholly wing** is compared strictly — that is
      the gradient, the corner radius and the wing's fill, i.e. everything except the edge;
    * the **width of the edge band itself** is bounded. A wing drawn at the wrong scale or
      off-centre does not blur the boundary, it puts white where the reference has plate, and
      those pixels are counted in the strict classes above; a boundary that is genuinely just
      softer shows up here and nowhere else.

    So a mis-scaled, mis-placed, mis-coloured or mis-shaped icon still fails.
    """
    reference = Image.open(LEGACY).convert("RGBA")
    side = reference.size[0]
    rendered = icon(ends, mask, side)
    classes = _wing(mask, side).load()

    solid = drifted = worst = edge = 0
    left, right = reference.load(), rendered.load()
    for y in range(side):
        for x in range(side):
            coverage = classes[x, y]
            if 5 <= coverage <= 250:
                edge += 1
                continue
            solid += 1
            delta = max(abs(a - b) for a, b in zip(left[x, y], right[x, y]))
            worst = max(worst, delta)
            if delta > MAX_CHANNEL_DRIFT:
                drifted += 1

    drift_share = drifted / solid
    edge_share = edge / (side * side)
    print(
        f"  checked against {LEGACY.relative_to(ROOT)}: "
        f"{drift_share:.3%} of {solid:,} solid pixels over {MAX_CHANNEL_DRIFT} "
        f"(worst {worst}), edge band {edge_share:.2%}"
    )
    if drift_share > MAX_DRIFTING_PIXELS:
        sys.exit(
            f"the reconstruction no longer matches the launcher icon: {drift_share:.3%} of "
            f"solid pixels drift by more than {MAX_CHANNEL_DRIFT} levels (worst {worst}). "
            "Something in make_launcher_icons.py moved; reconcile the two before shipping."
        )
    if edge_share > MAX_EDGE_SHARE:
        sys.exit(
            f"the wing's edge covers {edge_share:.2%} of the icon, over {MAX_EDGE_SHARE:.0%} — "
            "the silhouette is the wrong size or in the wrong place, not merely softer."
        )


def write_icns(images, path):
    """An `.icns`, by hand.

    Pillow can read one and cannot portably write one. The container is trivial — a magic,
    a total length, then typed chunks — and every type used here takes a PNG payload, so this
    is a handful of `struct.pack` calls rather than a dependency that only works on a Mac.
    Which matters: the release job builds this on Linux.
    """
    chunks = []
    for ostype, size in ICNS_TYPES:
        payload = _png_bytes(images[size])
        chunks.append(ostype + struct.pack(">I", len(payload) + 8) + payload)
    body = b"".join(chunks)
    path.write_bytes(b"icns" + struct.pack(">I", len(body) + 8) + body)


def _png_bytes(image):
    import io

    buffer = io.BytesIO()
    image.save(buffer, format="PNG")
    return buffer.getvalue()


def main():
    if not LEGACY.exists() or not FOREGROUND.exists():
        sys.exit(f"the launcher icons are missing from {RES.relative_to(ROOT)}")

    mask = wing_mask()
    ends = gradient_ends()
    print(f"plate gradient: #{'%02X%02X%02X' % ends[0]} to #{'%02X%02X%02X' % ends[1]}")
    verify(ends, mask)

    wanted = sorted({size for _, size in ICNS_TYPES} | set(ICO_SIZES) | {PNG_SIZE})
    images = {size: icon(ends, mask, size) for size in wanted}

    OUT.mkdir(parents=True, exist_ok=True)
    images[PNG_SIZE].save(OUT / "tto.png")
    # Pillow writes every requested size into one .ico, which is what Windows wants: the
    # shell picks the entry closest to the size it is drawing rather than rescaling one.
    images[max(ICO_SIZES)].save(OUT / "tto.ico", sizes=[(s, s) for s in ICO_SIZES])
    write_icns(images, OUT / "tto.icns")

    for name in ("tto.png", "tto.ico", "tto.icns"):
        written = OUT / name
        print(f"  {written.relative_to(ROOT)}  {written.stat().st_size:,} bytes")


if __name__ == "__main__":
    main()
